insert_at_begining
if there is not a single elements and we try to implement insert_at_begining its showing elf.head.prev = node
AttributeError: 'NoneType' object has no attribute 'prev' so .Hence if condition in added